sudo: false
language: scala
scala:
   - 2.12.3
   - 2.11.11
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - sbt clean coverage test
after_success:
  - pip install --user codecov && codecov
